# SPDX-FileCopyrightText: Copyright (C) 2023 NOI Techpark
# SPDX-License-Identifier: AGPL-3.0-or-later
name: CI/CD

on:
  push:
  pull_request:

env:
  AWS_REGION : "eu-west-1"

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      HOME: '.'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    env:
      AWS_S3_BUCKET_NAME : "opendatahub-bootcamp-website"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Copy to dist folder
        run: cp -a ./public/. ./dist/

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist

  